[2025-04-07T08:52:51.679+0000] {processor.py:161} INFO - Started process (PID=293) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:52:51.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:52:51.689+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:52:51.687+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:52:54.338+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:52:54.331+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:52:54.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:52:54.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 2.709 seconds
[2025-04-07T08:53:25.161+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:53:25.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:53:25.162+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:53:25.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:53:25.698+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:53:25.697+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:53:25.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:53:25.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.553 seconds
[2025-04-07T08:53:56.445+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:53:56.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:53:56.447+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:53:56.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:53:56.986+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:53:56.985+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:53:56.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:53:56.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.558 seconds
[2025-04-07T08:54:27.714+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:54:27.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:54:27.716+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:54:27.716+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:54:28.271+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:54:28.269+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:54:28.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:54:28.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.575 seconds
[2025-04-07T08:54:58.939+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:54:58.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:54:58.941+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:54:58.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:54:59.468+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:54:59.467+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:54:59.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:54:59.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.546 seconds
[2025-04-07T08:55:30.178+0000] {processor.py:161} INFO - Started process (PID=405) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:55:30.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:55:30.179+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:55:30.179+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:55:30.712+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:55:30.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:55:30.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:55:30.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.550 seconds
[2025-04-07T08:56:01.356+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:56:01.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:56:01.360+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:56:01.360+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:56:02.798+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:56:02.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:56:02.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:56:02.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 1.469 seconds
[2025-04-07T08:56:33.689+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:56:33.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:56:33.691+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:56:33.691+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:56:34.221+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:56:34.220+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:56:34.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:56:34.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.548 seconds
[2025-04-07T08:57:04.833+0000] {processor.py:161} INFO - Started process (PID=471) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:57:04.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:57:04.835+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:57:04.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:57:05.374+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:57:05.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:57:05.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:57:05.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.559 seconds
[2025-04-07T08:57:36.315+0000] {processor.py:161} INFO - Started process (PID=493) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:57:36.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:57:36.317+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:57:36.317+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:57:36.858+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:57:36.856+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:57:36.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:57:36.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.560 seconds
[2025-04-07T08:58:07.561+0000] {processor.py:161} INFO - Started process (PID=515) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:58:07.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:58:07.564+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:58:07.562+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:58:08.105+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:58:08.104+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:58:08.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:58:08.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.560 seconds
[2025-04-07T08:58:38.795+0000] {processor.py:161} INFO - Started process (PID=537) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:58:38.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:58:38.798+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:58:38.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:58:39.328+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:58:39.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:58:39.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:58:39.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.549 seconds
[2025-04-07T08:59:10.087+0000] {processor.py:161} INFO - Started process (PID=559) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:59:10.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:59:10.088+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:59:10.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:59:10.663+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:59:10.661+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:59:10.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:59:10.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.592 seconds
[2025-04-07T08:59:41.334+0000] {processor.py:161} INFO - Started process (PID=581) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:59:41.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T08:59:41.336+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:59:41.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:59:41.864+0000] {logging_mixin.py:188} INFO - [2025-04-07T08:59:41.862+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T08:59:41.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T08:59:41.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.546 seconds
[2025-04-07T09:00:12.527+0000] {processor.py:161} INFO - Started process (PID=603) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T09:00:12.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T09:00:12.529+0000] {logging_mixin.py:188} INFO - [2025-04-07T09:00:12.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T09:00:13.293+0000] {logging_mixin.py:188} INFO - [2025-04-07T09:00:13.290+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T09:00:13.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T09:00:13.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.787 seconds
[2025-04-07T15:05:59.370+0000] {processor.py:161} INFO - Started process (PID=122921) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:05:59.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:05:59.375+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:05:59.374+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:06:00.720+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:06:00.714+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:06:00.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:06:00.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 1.385 seconds
[2025-04-07T15:06:31.069+0000] {processor.py:161} INFO - Started process (PID=122945) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:06:31.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:06:31.078+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:06:31.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:06:31.947+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:06:31.945+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:06:31.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:06:31.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.931 seconds
[2025-04-07T15:07:02.662+0000] {processor.py:161} INFO - Started process (PID=122967) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:02.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:07:02.664+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:07:02.663+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:03.348+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:07:03.344+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:07:03.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:03.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.725 seconds
[2025-04-07T15:07:16.485+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:16.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:07:16.490+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:07:16.490+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:18.651+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:07:18.648+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:07:18.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:18.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 2.186 seconds
[2025-04-07T15:07:34.154+0000] {processor.py:161} INFO - Started process (PID=122989) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:34.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:07:34.158+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:07:34.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:35.523+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:07:35.518+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:07:35.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:35.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 1.395 seconds
[2025-04-07T15:07:48.775+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:48.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:07:48.776+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:07:48.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:49.619+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:07:49.617+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:07:49.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:07:49.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.860 seconds
[2025-04-07T15:08:06.350+0000] {processor.py:161} INFO - Started process (PID=123011) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:06.351+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:08:06.353+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:08:06.352+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:07.352+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:08:07.349+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:08:07.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:07.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 1.038 seconds
[2025-04-07T15:08:19.929+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:19.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:08:19.932+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:08:19.931+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:20.505+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:08:20.504+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:08:20.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:20.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.592 seconds
[2025-04-07T15:08:37.641+0000] {processor.py:161} INFO - Started process (PID=123033) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:37.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:08:37.644+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:08:37.643+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:38.012+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:08:38.010+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:08:38.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:08:38.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.388 seconds
[2025-04-07T15:09:08.998+0000] {processor.py:161} INFO - Started process (PID=123055) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:09:08.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:09:09.000+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:09:08.999+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:09:09.352+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:09:09.350+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:09:09.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:09:09.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.371 seconds
[2025-04-07T15:09:40.251+0000] {processor.py:161} INFO - Started process (PID=123083) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:09:40.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:09:40.253+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:09:40.253+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:09:40.630+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:09:40.629+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:09:40.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:09:40.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.396 seconds
[2025-04-07T15:10:11.442+0000] {processor.py:161} INFO - Started process (PID=123106) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:10:11.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:10:11.444+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:10:11.444+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:10:11.790+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:10:11.788+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:10:11.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:10:11.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.365 seconds
[2025-04-07T15:10:41.873+0000] {processor.py:161} INFO - Started process (PID=123128) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:10:41.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:10:41.875+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:10:41.875+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:10:42.237+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:10:42.236+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:10:42.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:10:42.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.382 seconds
[2025-04-07T15:11:13.176+0000] {processor.py:161} INFO - Started process (PID=123150) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:11:13.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:11:13.179+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:11:13.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:11:13.547+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:11:13.545+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:11:13.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:11:13.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.388 seconds
[2025-04-07T15:11:44.531+0000] {processor.py:161} INFO - Started process (PID=123172) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:11:44.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:11:44.534+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:11:44.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:11:44.895+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:11:44.893+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:11:44.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:11:44.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.388 seconds
[2025-04-07T15:12:14.973+0000] {processor.py:161} INFO - Started process (PID=123194) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:12:14.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:12:14.975+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:12:14.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:12:15.335+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:12:15.333+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:12:15.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:12:15.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.379 seconds
[2025-04-07T15:12:46.271+0000] {processor.py:161} INFO - Started process (PID=123217) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:12:46.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:12:46.274+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:12:46.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:12:46.629+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:12:46.627+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:12:46.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:12:46.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.378 seconds
[2025-04-07T15:13:17.447+0000] {processor.py:161} INFO - Started process (PID=123239) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:13:17.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:13:17.449+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:13:17.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:13:17.825+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:13:17.824+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:13:17.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:13:17.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.395 seconds
[2025-04-07T15:13:47.887+0000] {processor.py:161} INFO - Started process (PID=123261) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:13:47.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:13:47.888+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:13:47.888+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:13:48.225+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:13:48.224+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:13:48.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:13:48.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.355 seconds
[2025-04-07T15:14:19.172+0000] {processor.py:161} INFO - Started process (PID=123283) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:14:19.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:14:19.176+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:14:19.175+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:14:19.727+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:14:19.724+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:14:19.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:14:19.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.586 seconds
[2025-04-07T15:14:50.315+0000] {processor.py:161} INFO - Started process (PID=123305) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:14:50.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:14:50.317+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:14:50.317+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:14:50.670+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:14:50.668+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:14:50.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:14:50.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.371 seconds
[2025-04-07T15:15:21.671+0000] {processor.py:161} INFO - Started process (PID=123327) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:15:21.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:15:21.673+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:15:21.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:15:22.022+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:15:22.020+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:15:22.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:15:22.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.367 seconds
[2025-04-07T15:15:52.978+0000] {processor.py:161} INFO - Started process (PID=123349) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:15:52.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:15:52.979+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:15:52.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:15:53.339+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:15:53.337+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:15:53.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:15:53.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.377 seconds
[2025-04-07T15:16:24.301+0000] {processor.py:161} INFO - Started process (PID=123371) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:16:24.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:16:24.304+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:16:24.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:16:24.659+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:16:24.657+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:16:24.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:16:24.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.374 seconds
[2025-04-07T15:16:55.463+0000] {processor.py:161} INFO - Started process (PID=123393) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:16:55.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:16:55.465+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:16:55.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:16:55.826+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:16:55.824+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:16:55.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:16:55.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.380 seconds
[2025-04-07T15:17:25.994+0000] {processor.py:161} INFO - Started process (PID=123415) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:17:25.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:17:25.996+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:17:25.996+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:17:26.363+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:17:26.362+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:17:26.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:17:26.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.386 seconds
[2025-04-07T15:17:57.251+0000] {processor.py:161} INFO - Started process (PID=123438) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:17:57.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:17:57.253+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:17:57.253+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:17:57.604+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:17:57.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:17:57.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:17:57.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.369 seconds
[2025-04-07T15:18:28.553+0000] {processor.py:161} INFO - Started process (PID=123460) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:18:28.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:18:28.556+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:18:28.555+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:18:28.898+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:18:28.896+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:18:28.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:18:28.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.360 seconds
[2025-04-07T15:18:59.791+0000] {processor.py:161} INFO - Started process (PID=123482) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:18:59.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:18:59.793+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:18:59.793+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:19:00.223+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:19:00.221+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:19:00.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:19:00.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.449 seconds
[2025-04-07T15:19:31.075+0000] {processor.py:161} INFO - Started process (PID=123504) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:19:31.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:19:31.076+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:19:31.076+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:19:31.419+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:19:31.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:19:31.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:19:31.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.360 seconds
[2025-04-07T15:20:02.338+0000] {processor.py:161} INFO - Started process (PID=123526) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:20:02.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:20:02.342+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:20:02.342+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:20:02.805+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:20:02.803+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:20:02.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:20:02.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.493 seconds
[2025-04-07T15:20:33.586+0000] {processor.py:161} INFO - Started process (PID=123548) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:20:33.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:20:33.587+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:20:33.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:20:33.936+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:20:33.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:20:33.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:20:33.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.368 seconds
[2025-04-07T15:21:04.862+0000] {processor.py:161} INFO - Started process (PID=123570) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:21:04.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:21:04.864+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:21:04.864+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:21:05.241+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:21:05.240+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:21:05.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:21:05.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.398 seconds
[2025-04-07T15:21:36.162+0000] {processor.py:161} INFO - Started process (PID=123592) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:21:36.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:21:36.164+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:21:36.164+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:21:36.735+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:21:36.733+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:21:36.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:21:36.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.597 seconds
[2025-04-07T15:22:07.476+0000] {processor.py:161} INFO - Started process (PID=123614) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:22:07.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:22:07.479+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:22:07.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:22:08.052+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:22:08.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:22:08.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:22:08.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.599 seconds
[2025-04-07T15:22:38.654+0000] {processor.py:161} INFO - Started process (PID=123635) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:22:38.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:22:38.656+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:22:38.656+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:22:39.002+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:22:39.000+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:22:39.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:22:39.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.365 seconds
[2025-04-07T15:23:09.179+0000] {processor.py:161} INFO - Started process (PID=123657) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:23:09.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:23:09.181+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:23:09.181+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:23:09.577+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:23:09.575+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:23:09.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:23:09.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.415 seconds
[2025-04-07T15:23:40.578+0000] {processor.py:161} INFO - Started process (PID=123689) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:23:40.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:23:40.581+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:23:40.581+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:23:40.927+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:23:40.925+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:23:40.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:23:40.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.366 seconds
[2025-04-07T15:24:11.856+0000] {processor.py:161} INFO - Started process (PID=123717) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:24:11.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:24:11.858+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:24:11.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:24:12.216+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:24:12.214+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:24:12.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:24:12.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.376 seconds
[2025-04-07T15:24:43.007+0000] {processor.py:161} INFO - Started process (PID=123739) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:24:43.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:24:43.009+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:24:43.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:24:43.361+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:24:43.359+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:24:43.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:24:43.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.372 seconds
[2025-04-07T15:25:14.356+0000] {processor.py:161} INFO - Started process (PID=123761) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:25:14.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:25:14.358+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:25:14.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:25:14.723+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:25:14.722+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:25:14.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:25:14.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.384 seconds
[2025-04-07T15:25:45.621+0000] {processor.py:161} INFO - Started process (PID=123783) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:25:45.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:25:45.624+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:25:45.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:25:45.995+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:25:45.993+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:25:45.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:25:46.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.394 seconds
[2025-04-07T15:26:16.950+0000] {processor.py:161} INFO - Started process (PID=123805) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:26:16.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:26:16.951+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:26:16.951+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:26:17.343+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:26:17.341+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:26:17.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:26:17.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.411 seconds
[2025-04-07T15:26:48.237+0000] {processor.py:161} INFO - Started process (PID=123827) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:26:48.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:26:48.240+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:26:48.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:26:48.592+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:26:48.590+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:26:48.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:26:48.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.372 seconds
[2025-04-07T15:27:18.681+0000] {processor.py:161} INFO - Started process (PID=123849) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:27:18.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:27:18.683+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:27:18.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:27:19.042+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:27:19.040+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:27:19.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:27:19.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.379 seconds
[2025-04-07T15:27:49.990+0000] {processor.py:161} INFO - Started process (PID=123871) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:27:49.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:27:49.993+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:27:49.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:27:50.343+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:27:50.341+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:27:50.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:27:50.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.369 seconds
[2025-04-07T15:28:21.305+0000] {processor.py:161} INFO - Started process (PID=123893) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:28:21.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:28:21.307+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:28:21.306+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:28:21.665+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:28:21.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:28:21.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:28:21.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.376 seconds
[2025-04-07T15:28:52.597+0000] {processor.py:161} INFO - Started process (PID=123915) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:28:52.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:28:52.600+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:28:52.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:28:53.139+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:28:53.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:28:53.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:28:53.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.565 seconds
[2025-04-07T15:29:23.878+0000] {processor.py:161} INFO - Started process (PID=123937) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:29:23.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:29:23.879+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:29:23.879+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:29:24.227+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:29:24.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:29:24.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:29:24.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.368 seconds
[2025-04-07T15:29:55.156+0000] {processor.py:161} INFO - Started process (PID=123959) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:29:55.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:29:55.159+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:29:55.158+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:29:55.528+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:29:55.526+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:29:55.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:29:55.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.389 seconds
[2025-04-07T15:30:26.420+0000] {processor.py:161} INFO - Started process (PID=123981) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:30:26.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:30:26.421+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:30:26.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:30:26.784+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:30:26.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:30:26.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:30:26.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.381 seconds
[2025-04-07T15:30:57.691+0000] {processor.py:161} INFO - Started process (PID=124003) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:30:57.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:30:57.693+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:30:57.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:30:58.046+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:30:58.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:30:58.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:30:58.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.371 seconds
[2025-04-07T15:31:28.952+0000] {processor.py:161} INFO - Started process (PID=124025) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:31:28.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:31:28.954+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:31:28.954+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:31:29.311+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:31:29.309+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:31:29.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:31:29.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.375 seconds
[2025-04-07T15:34:44.308+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:34:44.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:34:44.324+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:34:44.318+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:34:49.280+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:34:49.277+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:34:49.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:34:49.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 5.045 seconds
[2025-04-07T15:35:19.505+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:35:19.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:35:19.507+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:35:19.507+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:35:20.231+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:35:20.230+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:35:20.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:35:20.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.748 seconds
[2025-04-07T15:35:50.854+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:35:50.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:35:50.857+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:35:50.856+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:35:51.655+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:35:51.652+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:35:51.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:35:51.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.823 seconds
[2025-04-07T15:36:21.990+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:36:21.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/collect_match_info_dag.py for tasks to queue
[2025-04-07T15:36:21.992+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:36:21.991+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:36:22.525+0000] {logging_mixin.py:188} INFO - [2025-04-07T15:36:22.523+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/collect_match_info_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/collect_match_info_dag.py", line 37, in <module>
    API_KEYS = Variable.get('api_4_account_key_mix_1', deserialize_json=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_4_account_key_mix_1 does not exist'
[2025-04-07T15:36:22.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/collect_match_info_dag.py
[2025-04-07T15:36:22.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/collect_match_info_dag.py took 0.551 seconds
